### ISSUE TITLE
This repository should come with a public health warning

### ISSUE THREAD

**Issue by ashleybroughton** [Tangdongle/my_shrine_to_doug#1] opened 2018-07-19 04:09 UTC
Readers may experience sudden onset of extreme nausea and blindness.

**Comment by Tangdongle** [comment] 2018-07-19 04:13
This is working as intended. Closing this issue.

**Comment by Tangdongle** [comment] 2018-07-19 05:08
Upon closer inspection, a README with a PSA will enhance reader's warning bandwidth. Will update README

**Closed as completed** 2018-07-19 05:09 UTC
Labels: enhancement
